import type { AchievementType, AchievementConfig } from '@/types';

export const ACHIEVEMENTS: Record<AchievementType, AchievementConfig> = {
  first_line: {
    type: 'first_line',
    name: '初次連線',
    description: '完成第一條 Bingo 連線',
    icon: 'trophy',
    condition: '完成任意一條連線',
    maxProgress: 1,
  },
  first_fullhouse: {
    type: 'first_fullhouse',
    name: '首次全清',
    description: '首次完成所有 9 格',
    icon: 'star',
    condition: '完成所有格子',
    maxProgress: 1,
  },
  three_lines: {
    type: 'three_lines',
    name: '三連勝',
    description: '單日完成 3 條連線',
    icon: 'zap',
    condition: '一天內完成 3 條連線',
    maxProgress: 3,
  },
  five_lines: {
    type: 'five_lines',
    name: '五線譜',
    description: '單日完成 5 條連線',
    icon: 'award',
    condition: '一天內完成 5 條連線',
    maxProgress: 5,
  },
  week_streak: {
    type: 'week_streak',
    name: '週間勇士',
    description: '連續 7 天完成至少一條連線',
    icon: 'calendar',
    condition: '連續 7 天有連線',
    maxProgress: 7,
  },
  month_streak: {
    type: 'month_streak',
    name: '月度冠軍',
    description: '連續 30 天完成至少一條連線',
    icon: 'crown',
    condition: '連續 30 天有連線',
    maxProgress: 30,
  },
  combo_3x: {
    type: 'combo_3x',
    name: '連擊新手',
    description: '達成 3 倍連擊',
    icon: 'flame',
    condition: '連續完成 3 個任務',
    maxProgress: 3,
  },
  combo_5x: {
    type: 'combo_5x',
    name: '連擊大師',
    description: '達成最高 5 倍連擊',
    icon: 'fire',
    condition: '連續完成 5 個任務',
    maxProgress: 5,
  },
  early_bird: {
    type: 'early_bird',
    name: '早起的鳥',
    description: '早上 8 點前完成 3 個任務',
    icon: 'sunrise',
    condition: '08:00 前完成 3 任務',
    maxProgress: 3,
  },
  night_owl: {
    type: 'night_owl',
    name: '夜貓子',
    description: '晚上 10 點後完成 3 個任務',
    icon: 'moon',
    condition: '22:00 後完成 3 任務',
    maxProgress: 3,
  },
  category_master_work: {
    type: 'category_master_work',
    name: '工作達人',
    description: '累計完成 50 個工作任務',
    icon: 'briefcase',
    condition: '完成 50 個工作任務',
    maxProgress: 50,
  },
  category_master_health: {
    type: 'category_master_health',
    name: '健康達人',
    description: '累計完成 50 個健康任務',
    icon: 'heart',
    condition: '完成 50 個健康任務',
    maxProgress: 50,
  },
  category_master_personal: {
    type: 'category_master_personal',
    name: '生活達人',
    description: '累計完成 50 個個人任務',
    icon: 'user',
    condition: '完成 50 個個人任務',
    maxProgress: 50,
  },
  category_master_learning: {
    type: 'category_master_learning',
    name: '學習達人',
    description: '累計完成 50 個學習任務',
    icon: 'book',
    condition: '完成 50 個學習任務',
    maxProgress: 50,
  },
  speed_demon: {
    type: 'speed_demon',
    name: '速度惡魔',
    description: '30 分鐘內完成全清',
    icon: 'rocket',
    condition: '30 分鐘內全清',
    maxProgress: 1,
  },
  perfectionist: {
    type: 'perfectionist',
    name: '完美主義者',
    description: '累計 10 次全清',
    icon: 'check-circle',
    condition: '累計全清 10 次',
    maxProgress: 10,
  },
  veteran: {
    type: 'veteran',
    name: '老手',
    description: '累計使用 100 天',
    icon: 'shield',
    condition: '使用滿 100 天',
    maxProgress: 100,
  },
};

export const COMBO_MULTIPLIERS: Record<number, number> = {
  1: 1,
  2: 1.5,
  3: 2,
  4: 2.5,
  5: 3,
};

export const MAX_COMBO = 5;

export const COMBO_TIMEOUT_MS = 30 * 60 * 1000; // 30 分鐘
